### ISSUE TITLE
`--no-hostonly-cmdline` is ignored when `--uefi` is set

### ISSUE THREAD

**Issue by prometheanfire** [dracutdevs/dracut#1012]
**Describe the bug**
`--no-hostonly-cmdline` is ignored when `--uefi` is set

**Distribution used**
Gentoo

**Dracut version**
51-r1 (includes patch for https://bugs.gentoo.org/760249)

**Init system**
systemd

**To Reproduce**
Use the following dracut config, the kernel_cmdline should not be necessary and additionally should be ignored when `no_hostonly_commandline="yes"` is set.

```
add_dracutmodules+=" zfs "
force_drivers+=" nvme zfs "
compress="zstd"

uefi_secureboot_cert="/etc/efikeys/db.crt"
uefi_secureboot_key="/etc/efikeys/db.key"
uefi_stub="/usr/lib/systemd/boot/efi/linuxx64.efi.stub"
uefi="yes"

kernel_cmdline="zfs.zfs_arc_max=3221225472 root=zfs:AUTO init=/usr/lib/systemd/systemd log_buf_len=2M psmouse.synaptics_intertouch=1 acpi_backlight=none ro"
no_hostonly_commandline="yes"
omit_dracutmodules+=" btrfs lvm qemu multipath i18n qemu-net lunmask resume "
omit_dracutmodules+=" plymouth "
```

**Expected behavior**
dracut does not set command line parameters when `no_hostonly_commandline="yes"` is set.

**Additional context**
There is no check for no_hostonly_commandline in this section of code.
https://github.com/dracutdevs/dracut/blob/c93df5e0ea18dabeeaa1955c0c66e315b3f3964a/dracut.sh#L2010-L2024 (permalinked from master as of `Mon Jan 18 03:51:11 AM UTC 2021`).  I'd suggest wrapping that whole section in a check, probably with another check at line 2033 (where it objcopies the cmdline into the image).

Is there a reason why a command line is always defined?  I generate a uefi binary in order to get signed kernel (the only way of doing so), but I do use systemd-boot to load the kernel images and do not use the generated unifed efi binary directly (meaning systemd-boot can pass kernel command line options).

Passing kernel command line options like this overrides those passed via an external bootloader (possibily by design).

**Comment by MuddyArch** [comment]
I would guess that it is because a unified kernel image by definition includes it and it's critical to have if you aren't using a bootloader (which I imagine most aren't).

Actually, I went back and did a quick look-over of some documentation, it seems I was generally correct.

Not just a definition, a specification 
https://systemd.io/BOOT_LOADER_SPECIFICATION/#type-2-efi-unified-kernel-images

> A valid unified kernel image must contain two PE sections:

    cmdline section with the kernel command line
    osrel section with an embedded copy of the os-release file describing the image


More importantly, you may want to look at https://wiki.archlinux.org/index.php/Systemd-boot#Adding_loaders

> Note: If options is present in a boot entry and Secure Boot is disabled, the value of options will override any .cmdline string embedded in the EFI image that is specified by efi or linux (see #Preparing a unified kernel image). With Secure Boot, however, options (and any edits made to the kernel command line in the bootloader UI) will be ignored, and only the embedded .cmdline will be used. 

So this looks like a planned feature beyond dracut's control. Plus, the point of signing a file is to show that it is unmodified, so even if you could I think you would have a different and worse issue.

But maybe I missed something and am wrong, I dunno, I got no sleep last night and I'm stuck at work.

That said, one of the Arch trusted users, Foxboron, has a side project he's been working on to make uefi/secureboot/signing more sane: https://github.com/Foxboron/sbctl

You might want to check it out, you won't need to make the .efi because you can just point sbctl at whatever you want to sign. If you keep a consistent name/path for the kernel images (not the autogenerated version names) you can save them into sbctl and it will check them when you run relevant commands.

I used sbctl with mkinitcpio, and I still use it after switching to dracut. It's hands down the easiest tool for signing I've used.

**Comment by prometheanfire** [comment]
Previously I was signing the kernel image itself (manually) with sbsign, that worked fine with defining options externally.  With that method I was having dracut generate a normal initramfs.  I'm not sure the command.  What the cmdline section seems to be doing is causing the options passed via systemdboot to be ignored.

https://www.kernel.org/doc/html/latest/admin-guide/efi-stub.html#passing-kernel-parameters-from-the-efi-shell states that kernel options should be accepted.

**Comment by johannbg** [comment]
@prometheanfire :thinking:  what happens if you change  no_hostonly_commandline to hostonly_cmdline="no"

**Comment by prometheanfire** [comment]
without no_hostonly_commandline set
with hostonly_cmdline="no" set
without kernel_cmdline set

```
dracut: *** Creating image file '/usr/src/linux-5.10.9/arch/x86/boot/initrd' ***
dracut: Using UEFI kernel cmdline:
dracut: nvmf.hostnqn=nqn.2014-08.org.nvmexpress:uuid:6f476451-25b8-4b64-b25b-5c8a1d74a7d3 nvmf.hostid=0aa971fa-dba8-4d70-b5d7-33fdd8c1f159
```

which would fail to boot

**Comment by prometheanfire** [comment]
opmiting the nvmf module causes the dracut kernel command line to be empty, which then causes dracut to hang (run in debug mode)

```
+ for moddir in "$dracutbasedir/modules.d"/[0-9][0-9]*
+ _d_mod=99uefi-lib
+ _d_mod=uefi-lib
+ [[ -n '' ]]
+ continue
+ unset moddir
+ echo -ne '\x00'
+ dinfo 'Using UEFI kernel cmdline:'
+ set +x
dracut: Using UEFI kernel cmdline:
++ tr -d '\000'
+ dinfo
+ set +x
```

**Comment by MuddyArch** [comment]
> Previously I was signing the kernel image itself (manually) with sbsign, that worked fine with defining options externally. With that method I was having dracut generate a normal initramfs. I'm not sure the command. What the cmdline section seems to be doing is causing the options passed via systemdboot to be ignored.
> 
> https://www.kernel.org/doc/html/latest/admin-guide/efi-stub.html#passing-kernel-parameters-from-the-efi-shell states that kernel options should be accepted.

So I've only been using Linux for a few months, so maybe I'm interpenetrating things incorrectly; if I am please let me know.

That link doesn't mention anything about secure boot or systemd. 

Besides the aliases and simple functions I've learned to make in these few months, I have zero coding experience. So I can't effectively parse [this](https://github.com/systemd/systemd/blob/main/src/boot/efi/stub.c)  to say whether it backs up what was said in the Arch wiki.

If it does, I would imagine that might be the issue. Because -

vmlinuz + initramfs = not a functional boot by themselves

efistub = lists everything you need for a functional boot

unified kernel = everything you need for a functional boot

And since you are signing them for secure boot, the latter two are locked from receiving any further modification as that would go against the purpose of secure boot (as they have/specify everything they need to boot). At least, that is my guess as for why it is like that, I don't actually know.

Hopefully this can be of some help, it was sort of like reading Spanish for me, in that I know some vocab and a bit of grammar and can kinda make out patterns.

Also, when I run dracut (I use a unified kernel) it doesn't make a new separate initramfs for me. I thought it might be the uefi stub and I added that to my config but just the .efi as well. Do you know what option sets that up? I'd like to play around with that incase my other theory fails.

**Comment by prometheanfire** [comment]
the separate EFI file is made (as an empty file) because tooling down the line requires it.

**Comment by prometheanfire** [comment]
I plan on modifying dracut to not require the cmdline portion and seeing what happens on boot (if options are taken from the bootloader (systemd-boot in this case)

**Comment by prometheanfire** [comment]
I can confirm that not inserting the cmdline section into the final uefi image seems to allow systemd-boot to pass kernel options to the efi binary.

the comments are the modifications I made (moved the `--add-section` line out of objcopy because bash).

```
if [[ $uefi = yes ]]; then
#    if [[ $kernel_cmdline ]]; then
#        echo -n "$kernel_cmdline" > "$uefi_outdir/cmdline.txt"
#    elif [[ $hostonly_cmdline = yes ]] && [ -d "$initdir/etc/cmdline.d" ];then
#        for conf in "$initdir"/etc/cmdline.d/*.conf ; do
#            [ -e "$conf" ] || continue
#            printf "%s " "$(< "$conf")" >> "$uefi_outdir/cmdline.txt"
#        done
#    else
#        do_print_cmdline > "$uefi_outdir/cmdline.txt"
#    fi
#    echo -ne "\x00" >> "$uefi_outdir/cmdline.txt"
#
#    dinfo "Using UEFI kernel cmdline:"
#    dinfo $(tr -d '\000' < "$uefi_outdir/cmdline.txt")

    [[ -s $dracutsysrootdir/usr/lib/os-release ]] && uefi_osrelease="$dracutsysrootdir/usr/lib/os-release"
    [[ -s $dracutsysrootdir/etc/os-release ]] && uefi_osrelease="$dracutsysrootdir/etc/os-release"
    [[ -s "${dracutsysrootdir}${uefi_splash_image}" ]] && \
        uefi_splash_image="${dracutsysrootdir}${uefi_splash_image}" || unset uefi_splash_image

#           --add-section .cmdline="${uefi_outdir}/cmdline.txt" --change-section-vma .cmdline=0x30000 \
    if objcopy \
           ${uefi_osrelease:+--add-section .osrel=$uefi_osrelease --change-section-vma .osrel=0x20000} \
           ${uefi_splash_image:+--add-section .splash="$uefi_splash_image" --change-section-vma .splash=0x40000} \
           --add-section .linux="$kernel_image" --change-section-vma .linux=0x2000000 \
           --add-section .initrd="${DRACUT_TMPDIR}/initramfs.img" --change-section-vma .initrd=0x3000000 \
           "$uefi_stub" "${uefi_outdir}/linux.efi"; then
```

https://gist.github.com/e1eb69f6c77d2d075c280fc9e6930676 is the reconfigure (gentoo stuff and dracut run without debug, because 1.2M text file is too much...)

**Comment by prometheanfire** [comment]
Here's an updated diff that works well (works if a user sets a cmdline and does nothing if one is not set).  The kernel does not allow the cmdline to be overridden if one is defined in the uefi image.  The patchset allows for no cmdline to be set (instead of force setting one if none is provided).

I can submit this if you want...

```patch
--- /usr/bin/dracut      2021-01-12 13:12:44.366062666 -0600
+++ /usr/bin/dracut.new  2021-01-27 20:30:34.449459182 -0600
@@ -2015,13 +2015,16 @@
             [ -e "$conf" ] || continue
             printf "%s " "$(< "$conf")" >> "$uefi_outdir/cmdline.txt"
         done
-    else
-        do_print_cmdline > "$uefi_outdir/cmdline.txt"
     fi
-    echo -ne "\x00" >> "$uefi_outdir/cmdline.txt"

-    dinfo "Using UEFI kernel cmdline:"
-    dinfo $(tr -d '\000' < "$uefi_outdir/cmdline.txt")
+    if [[ $kernel_cmdline ]] || [[ $hostonly_cmdline = yes && -d "$initdir/etc/cmdline.d" ]]; then
+        echo -ne "\x00" >> "$uefi_outdir/cmdline.txt"
+        dinfo "Using UEFI kernel cmdline:"
+        dinfo $(tr -d '\000' < "$uefi_outdir/cmdline.txt")
+       uefi_cmdline="--add-section .cmdline="${uefi_outdir}/cmdline.txt" --change-section-vma .cmdline=0x30000"
+    else
+        uefi_cmdline=""
+    fi

     [[ -s $dracutsysrootdir/usr/lib/os-release ]] && uefi_osrelease="$dracutsysrootdir/usr/lib/os-release"
     [[ -s $dracutsysrootdir/etc/os-release ]] && uefi_osrelease="$dracutsysrootdir/etc/os-release"
@@ -2030,7 +2033,7 @@

     if objcopy \
            ${uefi_osrelease:+--add-section .osrel=$uefi_osrelease --change-section-vma .osrel=0x20000} \
-           --add-section .cmdline="${uefi_outdir}/cmdline.txt" --change-section-vma .cmdline=0x30000 \
+          ${uefi_cmdline} \
            ${uefi_splash_image:+--add-section .splash="$uefi_splash_image" --change-section-vma .splash=0x40000} \
            --add-section .linux="$kernel_image" --change-section-vma .linux=0x2000000 \
            --add-section .initrd="${DRACUT_TMPDIR}/initramfs.img" --change-section-vma .initrd=0x3000000 \
```
