### ISSUE TITLE
Restore logrotate file

### ISSUE THREAD

**Issue by thesamesam** [dracutdevs/dracut#1112]
**Describe the bug**
Dracut's logrotate file/configuration was dropped in #1006. Please consider restoring this as not all distributions are using systemd. Some distributions allow a choice between systemd and e.eg. OpenRC, while some prefer to use OpenRC completely.

Would it be possible to restore this small file to allow consistency in the logrotate configuration used by these distributions (Gentoo Linux and Alpine Linux come to mind, but there are plenty of others)?

**Distribution used**
Gentoo Linux.

**Dracut version**
052

**Init system**
OpenRC.

In Gentoo, this is optional, but some distributions like e.g. Alpine do not use systemd at all.

**Comment by johannbg** [comment]
It's better that those ca 10 active linux distribution that use alternative init system to systemd or support multiple init system carry patches to include stuff like logrotate and or otherwise tailor their distribution to it's init system or multiple init systems rather than having those ca 200 active linux distribution that only use systemd having to potentially patch that file out. 

It cost the linux ecosystem less contributing time doing that way.

Here upstream, the built in systemd-journal logrotation costs us nothing ( no time or resources ) while logrotation solutions like logrotate costs us having to carry and thus test if logrotation, works times the factor of syslog implementations available out there, the contributors, the wait time for those test times to complete on their PR's and the infrastructure resources required to run those tests  etc. ( zero cost vs cost ).

**Comment by haraldh** [comment]
Here it is:
https://raw.githubusercontent.com/dracutdevs/dracut/77630365aed201a729c73a9ffda0733a75f3fee4/dracut.logrotate
