### ISSUE TITLE
I have installed anaconda-dracut but runing dracut --add "anaconda"  reports that "not install anaconda modules"

### ISSUE THREAD

**Issue by GitSoftwareNow** [dracutdevs/dracut#1118]
run dracut --list-modules ,the anaconda module in the list

**Comment by johannbg** [comment]
The example how to add a module can be found in dracut's man page. see ```man dracut```
Just ensure that the dracut module is available by installing the anaconda-dracut rpm and make sure that the source repo for anaconda has the anaconda-dracut rpm in it, which probably will trigger this error as well if it's missing.

In anycase dracut does not ship or otherwise maintain the anaconda module, so consult anaconda's documentation, or contact the anaconda list for any question(s) or file an issue with anaconda upstream, if you are experiencing an issues with the dracut module they provide.
