### ISSUE TITLE
dracut: dracut module 'anaconda' cannot be found or installed.

### ISSUE THREAD

**Issue by zslovezst** [dracutdevs/dracut#1119]
when I excute command "dracut --list-modules | grep anaconda",certainly it has。
So,how  can I fix it now?

**Comment by johannbg** [comment]
The example how to add a module which can be found in dracut's man page. see ```man dracut```
Just ensure that the dracut module is available by installing the anaconda-dracut rpm and make sure that the source repo for anaconda has the anaconda-dracut rpm in it, which probably will trigger this error as well if it's missing.

In anycase dracut does not ship or otherwise maintain the anaconda module, so consult anaconda's documentation, or contact the anaconda list for any question(s) or file an issue with anaconda upstream, if you are experiencing an issues with the dracut module they provide.

**Comment by GitSoftwareNow** [comment]
Me too
