### ISSUE TITLE
dracut command line `--omit` flag is not cumulative in relation to `/etc/dracut.conf.d/*.conf` config files

### ISSUE THREAD

**Issue by davidcassany** [dracutdevs/dracut#1341]
**Describe the bug**
When using the `--omit "module"` flag on the dracut command line it overrides any omit module statement that was already present in `/etc/dracut.conf.d/*`. I did not expect this behavior since `omit_dracutmodules` is also cumulative over all config files.

Probably this is a feature instead of a bug, however at the moment I can't really see why it is desirable the current behavior in contrast to a cumulative behavior. I find it really not intuitive and after reading the man pages one has the impression that `--add` and  `--omit` work in an equivalent way, cumulative since both can be specified multiple times and both can also be specified as cumulative in config files.

Current behavior forces me to review all config files before making use of the `--omit` flag in the command line if my purpose was simply omitting an specific module.

**Distribution used**
openSUSE Tumbleweed

**Dracut version**
dracut-053

**Expected behavior**
I expected that making use of `--omit <module>` flag on the command line would instruct `dracut` to create an image omitting the provided module and **also** omit any other module that is listed as part of `omit_dracutmodules` variable any `/etc/dracut.conf.d/*.conf`.

**Additional context**
This has been originally reported in https://github.com/OSInside/kiwi/issues/1751. KIWI is an appliance builder and we make use of `--omit` flag to omit, for instance, the `multipath` module. This helps us on making sure some firstboot deployment specific modules are not interfered with `multipath`, however we do not aim to completely prevent `multipath` module as a persistent config in `/etc/dracut.conf.d` in the resulting appliance image.

**Comment by johannbg** [comment]
When you chose to omit a module via --omit <module> then you are literally just stating that you want to omit that exact module It's addition to what is in other configuration file(s) 

Expecting that all omit_dracutmodules variable in /etc/dracut.conf or any configuration file that resides in /etc/dracut.conf.d/* cleared in the process is somewhat of an weird expectation.

What you are probably wanting here is somekind of clear all config file entry switch?

**Comment by johannbg** [comment]
Note that your expectation and the one in the issue that you refer to differ `kiwi calls dracut with --omit " multipath ", but that makes it ignore omit_dracutmodules in config files." ` which kinda makes this a bug ( or you already have your feature )

**Comment by Vogtinator** [comment]
> Might be the bug/feature is simply lack of plus and a space as in line 948 in dracut.sh which looks like this

It's not really a bug, this was intentionally done that way, as the `# these options override the stuff in the config file` comment indicates. While IMO it's surprising and undocumented, changing it would be an incompatible behaviour change.

**Comment by johannbg** [comment]
@Vogtinator well this is wrong behavior since adding and removing a module should behave in the exact same manner ( with the only exception being one adds and the other removes ) which makes it a bug. 

And there is no way to properly fix this behavior without introducing incompatible behavior and maybe introduce a new command ( --omit-modules? ) that does the previous omit behavior should it be desired but I personally would just want to wait and see if someone requests it since this bug has gone unnoticed for 12 years, which indicates that people arent omitting modules both from the cli and in configuration files, at the same time as in they either chose to do it only from the cli or only in configuration files and in those two usecases the behavior is unchanged.

@haraldh can probably give some historic context why this ended up being done like this ( he introduced it in 2009 ) when he returns after Easter. ( probably Tuesday ) but that does not change the fact this is the wrong behavior.
