### ISSUE TITLE
network module relies on arping

### ISSUE THREAD

**Issue by ptx0** [dracutdevs/dracut#135]
arping2 has superceded arping in Gentoo and the arguments have changed so a simple symlink doesn't work.

there is no `-f` equivalent in arping2, to accept only the first received response.

`-D` becomes `-d` for duplicate IPs
```
            if ! arping2 -q -d -c 2 -i $netif $new_ip_address ; then
```
this should ideally support both arping and arping2.

**Comment by puleglot** [comment]
> arping2 has superceded arping in Gentoo
That's not true. You can still emerge `net-misc/iputils` with `USE=arping`. I guess that `arping` binary provided by `net-analyzer/arping` (https://github.com/ThomasHabets/arping) was renamed to `arping2` to avoid collisions with `net-misc/iputils`.

The problem is that in `>=net-analyzer/arping-2.16` arping binary was renamed back to `arping`. So we should probably check the output of arping -h.

**Comment by haraldh** [comment]
oh my... who had the thought that having the same binary with totally different options is a good idea??????

**Comment by kpande** [comment]
this is not fixed.
