### ISSUE TITLE
NetworkManager dbus config can be in /etc

### ISSUE THREAD

**Issue by mikhailnov** [dracutdevs/dracut#1403]
Fedora adds a configure option when building NetworkManager to put dbus configs into /usr/share/dbus-1/system.d, but, by default, NetworkManagers puts them into /etc/dbus-1/systemd.d

I have relocated them to /usr/share as a better place in ROSA Linux instead of patching dracut, but I think default location should be considered.

**Comment by johannbg** [comment]
@mikhailnov I'm going to call in the cavalry @dustymabe @bengal can maybe shed some light on this since nothing should be placed into `/etc` in a modern OS design ( by default ) since /etc directory hierarchy should be considered none existent in today's age and it's very odd that NM is using /etc as opposed to /usr

**Comment by bengal** [comment]
The default path for D-Bus service files is `/etc/dbus-1/system.d/` for historical reasons (from what I understand, older versions of D-Bus daemon didn't support `/usr`). I filed:

 https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/831

to change the default to `/usr`. Note that distros can alread set a different path at build time (as Fedora does). I don't know about other distros, but I can say that RHEL7 and RHEL8 currently use `/etc`; therefore I think the dracut module should check both locations.

**Comment by johannbg** [comment]
The dbus specification is quite clear where dbus files should be located and we should follow that. 

If upstream in general start allowing workarounds for distributions that place files randomly over the file system hierarchy it kinda renders the effort people that created the specifications and those that follow these specifications mute.

On top of that it increases maintenance load which is why it's best to leave those that exist outside any specifications to carry all that burden themselves.

The correct way here is for the relevant distribution to fix this not for us to workaround it because it doesn't.

That said the module setup for nm is missing a host only section which should pick any nm related files up from /etc including the dbus one so by adding it, it could solve this issue.

**Comment by mikhailnov** [comment]
28.04.2021 20:05, Jóhann B. Guðmundsson пишет:
>
> The dbus specification is quite clear where dbus files should be located and we should follow that.
>
> If upstream in general start allowing workarounds for distributions that place files randomly over the file system hierarchy it kinda renders the effort people that created the specifications and those that follow these specifications mute.
>
Sounds reasonable.

**Comment by johannbg** [comment]
This should not be an issue if the host only section is added and if the relevant distribution defaults to host only setting like Fedora did back in 2013 but again I strongly recommend that the relevant distribution simply fixes this as opposed to work around it like that.

**Comment by johannbg** [comment]
The patch @bengal proposed to NM upstream has long since been merged upstream hence closing
