### ISSUE TITLE
info() destination in dracut-lib

### ISSUE THREAD

**Issue by jcflack** [dracutdevs/dracut#18]
dracut-lib defined `info` in such a way that it echoes to `stdout`.

Module writers have to be careful not to use `info` inside a function, if the function will be used in `$(...)` because the info message will then contaminate the function result instead of appearing at the console.

I would suggest either redefining`info` to write to `stderr` just as `warn` does (does the user care, or even have any way to find out, which messages appearing during boot were written to `stderr` and which to `stdout`?), or, if the `stdout`/`stderr` distinction really is important for some purpose I've missed, have `init.sh` do something very early on like:

``` sh
exec 9>&1
export DRACUT_INFO_FD=9
```

and have dracut-lib redefine `info` to `echo >&$DRACUT_INFO_FD`

... which would require being sure that no module code also does file descriptor opens using the same number, and whatever number is chosen is available at the chosen point in `init.sh`.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
