### ISSUE TITLE
Can't boot built kernel/initrd

### ISSUE THREAD

**Issue by miltmobley** [dracutdevs/dracut#208]
Hi, I have been building experimental kernels for opensuse 42.2; their install script finishes by running your program. To save time in 'make modules_install' I have been aggressively pruning the .config file to omit things I know I don't have or won't use, e.g. Infiniband, WiMax, etc.

But if I disable PCI_HOTPLUG, for example, the shpchp module isn't built. Your program reports this as an error, and the next restart hangs with a message like "runnng job on dev-by-id<disk-guid>...

If I do enable PCI_HOTPLUG, the module is built, your program does not report an error,
but it also does not report that it was included in the initrd. And the restart probably won't hang after
I fix the other cases.

How can I figure out exactly what programs will run during the boot?
I suspect from file ? that your may be running a service in the initrd to execute programs.
If this is true, how can I find out which programs will run?

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by miltmobley** [comment]
no longer working with opensuse
