### ISSUE TITLE
network-legacy without systemd local live ISO boot

### ISSUE THREAD

**Issue by LaszloGombos** [dracutdevs/dracut#2114]
**Describe the bug**
I have a problem that booting an ISO in a VM using qemu/kvm, the network is not configured properly. If I add a sleep 1 or udevadm settle before the rd.break=initqueue in 99base/init.sh everything works and eth0 gets an IP address. Without it, I the interface is named ens3 and it does not get an IP. I guess it's a corner case because on real hardware (on two notebooks) I had no problems. But looking at the init.sh code I seems reasonable to add udevadm settle (and not udevsettle) before the main loop.
I use network-legacy and no systemd dracut modules on my iso. But systemd-udevd is available in the initrd.

**Distribution used**
debian

**Dracut version**
57

**Init system**
systemd

**Comment by Mrfai** [comment]
Here are my logs. The problem is IMO that there's no /lib/dracut/hooks/initqueue/ifup-eth0.sh but only the ifup-lo.sh
I do not use root=/dev/nfs, since I boot from ISO and use the root filesystem from the ISO (it's a squashfs), no nfs. But I still set rd.neednet=1. This is the /proc/cmdline

BOOT_IMAGE=/boot/vmlinuz FAI_FLAGS=menu,verbose,createvt FAI_ACTION=install FAI_CONFIG_SRC=file:///var/lib/fai/config rd.live.image root=live:CDLABEL=FAI_CD rd.neednet ip=dhcp rd.debug

[init.log](https://github.com/dracutdevs/dracut/files/10200739/init.log)
[rdsosreport.txt](https://github.com/dracutdevs/dracut/files/10200740/rdsosreport.txt)

**Comment by Mrfai** [comment]
This only  occurs in the dmesg output (I'm not using systemd) during boot when the network is not configured properly:
[    4.432306] virtio_net virtio0 ens3: renamed from eth0
Therefore I have ens3 with not IP address. When adding the patch (udevadm settle) the I have a eth0 and no rename in dmesg output

**Comment by Mrfai** [comment]
No, it does not help. The network interface is now called eth0 but still does not get an IP address.

**Comment by Mrfai** [comment]
the nfs module is included because I'm using the same initrd (and the root file system) for both booting from network (via root=/dev/nfs) and  from an ISO.
