### ISSUE TITLE
Add support for kernel space BOOTSPLASH

### ISSUE THREAD

**Issue by tpgxyz** [dracutdevs/dracut#305]
Add support for kernel-space BOOTSPLASH

https://patchwork.kernel.org/patch/10026659/

dracut should check if these are set in kernel config
CONFIG_BOOTSPLASH=y
CONFIG_BOOTSPLASH_FILE="/bootsplash"

dracut should copy a splash file to initrd into a defined place based on kernel config.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by tpgxyz** [comment]
Looks like kernel-space bootsplash did not make into anything more than a patch series.

**Comment by danimo** [comment]
Yes, unfortunately. Thanks for closing!
