### ISSUE TITLE
dracut is English only

### ISSUE THREAD

**Issue by GravisZro** [dracutdevs/dracut#469]
Dracut only has strings in English and there is currently no way to provide string translations.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by GravisZro** [comment]
Still no translation lookup implemented.

**Comment by johannbg** [comment]
After careful consideration we have decided not to provide any string translations in dracut hence closing.

Thank you for your report.

**Comment by Vistaus** [comment]
That's too bad. I would love to translate it to Dutch.
