### ISSUE TITLE
bashisms in /bin/sh scripts

### ISSUE THREAD

**Issue by GravisZro** [dracutdevs/dracut#542]
Several module scripts reference `#!/bin/sh` but then go on to use Bash specific syntax.  In addition to being technically incorrect, others (and myself) have been bitten by this nasty bug.

https://bugzilla.redhat.com/show_bug.cgi?id=1676988

One user points out that "when [bash 5] is called via /bin/sh symlink, then POSIX mode is enabled."

**Comment by tombriden** [comment]
I've also been affected by this since updating to bash-5. I've tested 2 fixes, one suggested in the debian bug report and the other used by Void Linux, either work fine though not sure what the preferred would be:

https://github.com/void-linux/void-packages/blob/master/srcpkgs/dracut/patches/fix-bash-5.patch

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920563:
> The 3rd option could be easily accomplished by adding the following line
> to the top of /init (/usr/lib/dracut/modules.d/99base/init.sh) after the
> initial comment block:
> 
> `[ -f /bin/bash ] && [ "$BASH" = "/bin/sh" ] && exec /bin/bash /init`
