### ISSUE TITLE
allow LUKS containers to be mounted by name

### ISSUE THREAD

**Issue by ghost** [dracutdevs/dracut#550]
As of Fedora 29, dracut doesn't allow LUKS containers to be mounted using their names/labels but only their UUIDs. The `dracut.cmdline` man page doesn't have an option called `rd.luks.name` and this makes mounted LUKS container look like 
![this](https://user-images.githubusercontent.com/47925053/53694406-58948400-3dd4-11e9-8b8d-6560cd3f4f57.png)
It would be great if dracut allows mounting LUKS containers using their labels instead of random strings of UUIDs.

**Comment by Neurognostic** [comment]
I would enjoy this feature as well. Other initramfs generators, such as `mkinitcpio` with systemd hook allow defining the device mapper name with the parameter: `rd.luks.name=<UUID>=<NAME>`

**Comment by Neurognostic** [comment]
I found out you can use the `systemd-cryptsetup-generator(8)` kernel command line options. So while its not documented by dracut, you can set the kernel parameter `rd.luks.name=<UUID>=name` to get a device mapper name `name`.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
