### ISSUE TITLE
rd.luks.key does not unlock non-root luks container in hostonly mode

### ISSUE THREAD

**Issue by shizonic** [dracutdevs/dracut#551]
If I use rd.luks.key=/mykeyfile in hostonly mode I get prompted for the password of my non-root luks container with the same keyfile on boot. as soon as I switch to hostonly="no" auto unlock works for any container with the same keyfile.

e.g.

/ on /dev/sda1 with keyfile /.key
swap on /dev/sda2 with keyfile /.key

crypttab (wich is included in initrd as well as the keyfile) looks like:
cryptroot /dev/sda1 /.key discard
cryptswap /dev/sda2 /.key discsrd

dracut cmdline holds:
... rd.luks.key=/.key:/dev/sda1 ...

I played around with a lot of different cmdline params, modules, etc. But only hostonly="no" + hostonly_cmdline="yes" works like expected.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
