### ISSUE TITLE
Handle non-existant /proc/modules

### ISSUE THREAD

**Issue by haraldh** [dracutdevs/dracut#56]
If the kernel is built without modules, /proc/modules does not exist

**Comment by marmarek** [comment]
FWIW, the same problem happens when `/proc` is not mounted at all (for example in some build chroot environment). Workaround of `touch /proc/modules` in that case works.

**Comment by martinmcclure** [comment]
I ran into this issue, since I am building kernels for certain machines without loadable module support. In hostonly mode, Dracut 049 gives the message: 
```
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
dracut-install: Could not get list of loaded modules: Unknown error -2. Switching to non-hostonly mode.

```
I would prefer the behavior to be that if in hostonly mode and /proc/modules does not exist, Dracut will not attempt to include any modules (and probably log a message about skipping modules due to absence of /proc/modules), but will stay in hostonly mode.

There *is* a workaround, but it's non-obvious and rather ugly. You have to both:

1. Specify no_kernel
2. Set DRACUT_KERNEL_MODALIASES to point to an empty file (the file must exist!)

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by martinmcclure** [comment]
This problem still reproduces in the latest Dracut (5da70385bc). Please keep this issue open if there is any chance of it ever being fixed.

**Comment by johannbg** [comment]
@martinmcclure I'll keep it open

**Comment by AJ-Ianozi** [comment]
This may be the same issue or related, but I built my kernel without any modules and tried running dracut v 053:
```
dracut --hostonly --kver 5.15.1-gentoo -f /boot/initramfs-5.15.1-gentoo.img
dracut: Cannot find module directory /lib/modules/5.15.1-gentoo/
dracut: and --no-kernel was not specified
```
My /lib/modules/ contains
```
/lib/modules/
├── build -> /usr/src/linux-5.15.1-gentoo
├── kernel
├── modules.order
└── source -> /usr/src/linux-5.15.1-gentoo
```
The workaround is creating a blank directory, `/lib/modules/5.15.1-gentoo`, and the command works.

**Comment by steffenweber** [comment]
> 2\. Set DRACUT_KERNEL_MODALIASES to point to an empty file (the file must exist!)

What is the best place to set this environment variable?

(I'm using Dracut on a Linux system without module support but want Dracut to generate a hostonly initramfs.)

**Comment by martinmcclure** [comment]
@steffenweber What I do is fairly crude, but works. I have is the file /usr/local/sbin/dracut, containing
```
export DRACUT_KERNEL_MODALIASES=/usr/src/DracutModAliases
/usr/bin/dracut /usr/src/initramfs.cpio-new

```
where /usr/src/initramfs.cpio-new is where I want the output sent.
That way I can just type `dracut` and get what I want. If you want to be able to give command line args to dracut you'd replace that line with something like
`/usr/bin/dracut $@`

**Comment by dl200010** [comment]
> [@steffenweber](https://github.com/steffenweber) What I do is fairly crude, but works. I have is the file /usr/local/sbin/dracut, containing
> 
> ```
> export DRACUT_KERNEL_MODALIASES=/usr/src/DracutModAliases
> /usr/bin/dracut /usr/src/initramfs.cpio-new
> ```
> 
> where /usr/src/initramfs.cpio-new is where I want the output sent. That way I can just type `dracut` and get what I want. If you want to be able to give command line args to dracut you'd replace that line with something like `/usr/bin/dracut $@`

I was able to put "DRACUT_KERNEL_MODALIASES=/usr/src/DracutModAliases" into /etc/env.d/00dracut and then run env-update to get it into the env variables, so I can just run dracut directly without a script. I also had to add "source /etc/profile" to the root's .bashrc, because it would lose the variable every time I "sudo su" in. I am running Gentoo.
