### ISSUE TITLE
No output when kmod_module_get_path fails in install_module

### ISSUE THREAD

**Issue by agronick** [dracutdevs/dracut#620]
I have --debug and --verbose turned on for dracut-install and this is the output I am getting:
```
dracut-install: Handle module 'nvidia'
dracut-install: ERROR: installing 'nvidia'
```
Thats it.

I had to add my own logging to find out its failing on kmod_module_get_path. A end user should be able to figure this out without compiling it. Please add debug logging on the error return codes in kmod_module_get_path.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
