### ISSUE TITLE
Pre-boot bonding doesnt failover properly.

### ISSUE THREAD

**Issue by shoughton1996** [dracutdevs/dracut#641]
When configuring bonding with dracut for a system utilizing NBDE, ive found that the disk will unlock if both the interfaces in the bond are up. When simulating  failover, i removed the 2nd nic cable, and the networking works fine but when relying on the secondary interface in the bond, it does not respond to networking. 

This occurs both in the initramfs phase as well as when the OS is fully booted. What i have found is that if you bounce the secondary bonded interface after the disk is unlocked, it will magically start responding on the network.

Command i used:

dracut -f --regenerate-all --kernel-cmdline "bond=bond:em1,em2:mode=active-backup ip=172.31.31.110::172.31.31.1:255.255.255.0::bond0:none:8.8.8.8"

Is this expected behavior or am i misconfiguring something?

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
