### ISSUE TITLE
Please document the directory structure when using persistant overlay

### ISSUE THREAD

**Issue by ytrezq** [dracutdevs/dracut#646]
While the device mapper persistant storage use files, the overlayfs based one use directories.

Of course using ᴅᴍ based persistant overlay with overlayfs enabled doesn’t works.

**Comment by FGrose** [comment]
See https://github.com/dracutdevs/dracut/blob/master/dracut.cmdline.7.asc#booting-live-images.
Perhaps also https://fedoraproject.org/wiki/LiveOS_image.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by ytrezq** [comment]
@johannbg of course, this documentation problem should be solved. But I m not having much to add.
