### ISSUE TITLE
How to execute shell script before rootfs mounted

### ISSUE THREAD

**Issue by Ankele** [dracutdevs/dracut#695]
When I install my OS, I chose to encryt my root lv, so I can protect my data even if the disk has been stolen. And this encryption operation should not be known by my user, so I set a rd.luks.key in kernel command line. But this file is plain(It's easy to expose passwords), and I can't add a GPG keyfile to the rootfs because rootfs should be automatically mounted and serviced directly on each boot, however the GPG keyfile ask for password.

The systemd developer suggested that I add a new dracut module, but I really don't know how to do it.
Another way to think about it is if I can execute a custom shell script before rootfs is mounted, even if just echo something, Because I do this in CentOS6 by executing shell scripts in init which contained in initramfs.img .

Looking forward to your help!

**Comment by haraldh** [comment]
Is this for a server, where you can't interactively provide the password via the keyboard?

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
