### ISSUE TITLE
network-manager module is not plumbing IPv6 networking using SLAAC

### ISSUE THREAD

**Issue by brianjmurrell** [dracutdevs/dracut#700]
In Fedora 30 dracut with an NFS root automatically plumbed IPv6 addresses using
SLAAC.  As of F31, it no longer does and in fact it sets `disable_ipv6=1`.

This is using dracut-049-27.git20181204.fc31.1.x86_64.

Accordingly I have reverted to network-legacy, but it has it's own issues.

My kernel command-line:

```
root=nfs:10.75.22.1:/clients/pvr-lr,rw,nfsvers=3 /dev/nfs
initrd=initrd.img-fedora-pxe ip=dhcp boot=nfs
```

I've even tried adding `ip=auto6` to the above (even though it has never been
necessary in the past) but that results in neither IPv4 nor IPv6 plumbing.

**Comment by bengal** [comment]
With the `ip=dhcp` commandline the network-manager module only
configures IPv4 and disables IPv6. This behavior seems expected to me;
can you elaborate on why you need IPv6 configured if the the NFS root
is accessed via IPv4?

The network-legacy module only starts DHCPv4 with ip=dhcp, but leaves
kernel IPv6 autoconf enabled and so SLAAC is performed by
kernel. However I don't think you can rely on the presence of an IPv6
address after the initqueue completes because the module doesn't wait
for it.

`ip=auto6` should work with network-manager. If it doesn't, please attach a log
captured with `rd.debug`. Thank you.

**Comment by brianjmurrell** [comment]
> can you elaborate on why you need IPv6 configured if the the NFS root
is accessed via IPv4?

It's not in fact.  The root (and all other) filesystems are accessed via IPv6.  I do see that in my original description I do have an IPv4 root file system specified.  I don't recall if that was a cut'n'pasto or historical.  But that this time, the kernel commandline is:

```
root=nfs:[fd31:aeb1:48df:0:3b14:e643:83d8:7017]:/clients/pvr-lr,rw,nfsvers=3 ip=enp4s0:dhcp initrd=initrd.img-fedora-pxe boot=nfs rd.retry=5
```

Additionally, once the initial IPv4 lease (the one it gets at the PXE boot) expires, it never renews it and is an IPv6-only node.

The only reason there is any IPv4 at all is that the NIC boot ROM only supports getting an IPv4 lease.

**Comment by bengal** [comment]
Since this used to work with the network module, perhaps we should change the NM initrd generator to enable kernel IPv6 autoconf with `ip=dhcp`. I'll prepare a patch.

Does IPv6 work if you set `ip=auto6`? If not, can you please attach NM logs captured with `rd.debug`?
