### ISSUE TITLE
Need to specify interface with ip= (and network-legacy) otherwise eth0 is assumed

### ISSUE THREAD

**Issue by brianjmurrell** [dracutdevs/dracut#701]
Due to [problems with the network-manager module](https://github.com/dracutdevs/dracut/issues/700) in Fedora 31 I had to revert to `network-legacy` but with it, `ip=dhcp` doesn't work as the initqueue interface plumbing script to bring up the NIC assumes it's called `eth0` by the kernel.

To work around this I had to use "ip=enp4s0:dhcp" to get the initqueue script to up `enp4s0` instead of the non-existent `eth0`.

It should support the non-explicit syntax, probe for the interface name(s) and bring them up by their proper name(s).

**Comment by brianjmurrell** [comment]
Anything/one here?

**Comment by haraldh** [comment]
Hmm, `eth*` is not hardcoded anywhere.

Please open a bugzilla bug and attach `/run/initramfs/rdsosreport.txt` booting with "rd.debug rd.shell" added to the kernel command line and reference the bugzilla here.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
