### ISSUE TITLE
Generate initramfs without chroot

### ISSUE THREAD

**Issue by RossComputerGuy** [dracutdevs/dracut#703]
I'm trying to add dracut to my OS which uses Buildroot, I've modified the fs part of Buildroot and I've got a script which should build the initramfs but I just cannot get it working. Any tips or help would be nice. This is what the script looks like:
```
#!/usr/bin/sh

export dracutbasedir=$HOST_DIR/lib/dracut
$HOST_DIR/bin/dracut -l --prefix $TARGET_DIR/boot --kver $(ls $TARGET_DIR/lib/modules)
```
And I'm using the 049 release.

**Comment by poldi871** [comment]
Hello,
I'm working on exactly the same problem a few days now, but still without success. I get an initramfs and dracut exits with 0, but the initramfs doesn't work, because there are missing some binaries which dracut doesn't find (find_binary). At the moment I'm still struggling with the various path-variables in dracut (PATH <-> DRACUT_PATH, etc.). Unfortunately it seems to be programmed according to the motto "It wasn't easy to write, so it should't be easy to read" ;-)
Some lines of comment describing the most important variables would be helpful.

Don't use version 049. It  is not prepared for cross-compiled environments. Use the current git-version. Have a look at the manual from the git-version. There are a lot of enties like "--sysroot".
It is a point to start, what environment to export before calling dracut from the BuildRoot environment.
Why do you think you need chroot?

Poldi

**Comment by haraldh** [comment]
dracut-050 now supports cross building... see README.cross

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
