### ISSUE TITLE
dracut does not reliably execute console_init from i18n module

### ISSUE THREAD

**Issue by ahesford** [dracutdevs/dracut#818]
Dracut provides options for handling console options (font, keymap, unicode/ASCII mode) in the `i18n` module (located in, *e.g.*, `/lib/dracut/modules.d/10i18n`). Inside the initramfs, the module installs the script `/lib/udev/console_init` to set these options according to the contents of `/etc/vconsole.conf`, which is populated by a `cmdline` hook that maps `rd.vconsole.*` kernel command-line options to values in this file (see `dracut.cmdline(7)` for more information). The module also installs a udev rule that will add a call to the `console_init` script as a dracut `initqueue` hook.

Unfortunately, execution of the `initqueue` hook is not guaranteed; the `initqueue` runloop continues until a number of predetermined "finish" conditions are satisfied. If these conditions are satisfied before the `initqueue` runloop has a chance to start, the `console_init` hook will never run (nor will other `initqueue` hooks).

Often, in a normal initramfs, this is not a problem, because there is minimal interaction with the user. However, if the user requests a breakpoint in the initramfs or a problem causes dracut to drop the user into an emergency shell, console options should be honored.

### Steps to reproduce:
1. Build a dracut image that does not rely on systemd (*e.g.*, on a Void Linux system) and has minimal initialization requirements (*e.g.*, just boots from a simple ext4 volume).
2. Boot the system with this image, settings a variable such as `rd.vconsole.font` to a custom font and setting `rd.break=pre-mount` to force dracut to drop to an emergency shell after the `initqueue` runloop has completed.

### Actual behavior
The console font displayed will be the default font.

### Excepted behavior:
The console font displayed should be the font selected by `rd.vconsole.conf`.

### Recommendation:
There are three ways to resolve this issue:
1. Instead of configuring `udev` (in `10i18n/10-console.rules`) to add the `console_init` script to the `initqueue`, just have `udev` execute the script directly;
2. Move `console_init` responsibilities outside the `initqueue` runloop or `udev` and add a specific hook for console initialization that is guaranteed to execute; or
3. Rearrange the `initqueue` runloop to try attempting its hooks at least once before checking the termination criteria.

**Comment by ahesford** [comment]
I haven't received any feedback on this issue, and don't believe it's been resolved.

**Comment by johannbg** [comment]
Just to give you a heads up and lower your expectation somewhat since I noticed that the distribution you are using is not using systemd and your issue may related to that, that there is no intention of dracut supporting multiple init system but instead the intent is to focus the limited resources available in the project to further integrate with and optimize dracut for systemd ( which is used by default or atleast available in all the primary linux distributions Arch,Debian,Fedora,Gentoo, OpenSuse most of their derivatives and other linux variants, ca 220 linux distribution in total ) and provide fallbacks for dracut's own init.sh. 
As things move forward the project will increasingly more reflect that so any issues that fall outside that scope will receive little to no attention.

**Comment by ahesford** [comment]
This might not be the proper forum, but I'm curious what benefits the dracut team perceives from tighter integration with systemd in the initramfs.

**Comment by johannbg** [comment]
Time.
